using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DrKlinik.Shared.DTO.Diagnose
{
    public class DiagnoseDTO
    {
        public float Itching { get; set; }
        public float SkinRash { get; set; }
        public float NodalSkinEruptions { get; set; }
        public float ContinuousSneezing { get; set; }
        public float Shivering { get; set; }
        public float Chills { get; set; }
        public float JointPain { get; set; }
        public float StomachPain { get; set; }
        public float Acidity { get; set; }
        public float UlcersOnTongue { get; set; }
        public float MuscleWasting { get; set; }
        public float Vomiting { get; set; }
        public float BurningMicturition { get; set; }
        public float SpottingUrination { get; set; }
        public float Fatigue { get; set; }
        public float WeightGain { get; set; }
        public float Anxiety { get; set; }
        public float ColdHandsAndFeets { get; set; }
        public float MoodSwings { get; set; }
        public float WeightLoss { get; set; }
        public float Restlessness { get; set; }
        public float Lethargy { get; set; }
        public float PatchesInThroat { get; set; }
        public float IrregularSugarLevel { get; set; }
        public float Cough { get; set; }
        public float HighFever { get; set; }
        public float SunkenEyes { get; set; }
        public float Breathlessness { get; set; }
        public float Sweating { get; set; }
        public float Dehydration { get; set; }
        public float Indigestion { get; set; }
        public float Headache { get; set; }
        public float YellowishSkin { get; set; }
        public float DarkUrine { get; set; }
        public float Nausea { get; set; }
        public float LossOfAppetite { get; set; }
        public float PainBehindTheEyes { get; set; }
        public float BackPain { get; set; }
        public float Constipation { get; set; }
        public float AbdominalPain { get; set; }
        public float Diarrhoea { get; set; }
        public float MildFever { get; set; }
        public float YellowUrine { get; set; }
        public float YellowingOfEyes { get; set; }
        public float AcuteLiverFailure { get; set; }
        public float FluidOverload { get; set; }
        public float SwellingOfStomach { get; set; }
        public float SwelledLymphNodes { get; set; }
        public float Malaise { get; set; }
        public float BlurredAndDistortedVision { get; set; }
        public float Phlegm { get; set; }
        public float ThroatIrritation { get; set; }
        public float RednessOfEyes { get; set; }
        public float SinusPressure { get; set; }
        public float RunnyNose { get; set; }
        public float Congestion { get; set; }
        public float ChestPain { get; set; }
        public float WeaknessInLimbs { get; set; }
        public float FastHeartRate { get; set; }
        public float PainDuringBowelMovements { get; set; }
        public float PainInAnalRegion { get; set; }
        public float BloodyStool { get; set; }
        public float IrritationInAnus { get; set; }
        public float NeckPain { get; set; }
        public float Dizziness { get; set; }
        public float Cramps { get; set; }
        public float Bruising { get; set; }
        public float Obesity { get; set; }
        public float SwollenLegs { get; set; }
        public float SwollenBloodVessels { get; set; }
        public float PuffyFaceAndEyes { get; set; }
        public float EnlargedThyroid { get; set; }
        public float BrittleNails { get; set; }
        public float SwollenExtremities { get; set; }
        public float ExcessiveHunger { get; set; }
        public float ExtraMaritalContacts { get; set; }
        public float DryingAndTinglingLips { get; set; }
        public float SlurredSpeech { get; set; }
        public float KneePain { get; set; }
        public float HipJointPain { get; set; }
        public float MuscleWeakness { get; set; }
        public float StiffNeck { get; set; }
        public float SwellingJoints { get; set; }
        public float MovementStiffness { get; set; }
        public float SpinningMovements { get; set; }
        public float LossOfBalance { get; set; }
        public float Unsteadiness { get; set; }
        public float WeaknessOfOneBodySide { get; set; }
        public float LossOfSmell { get; set; }
        public float BladderDiscomfort { get; set; }
        public float FoulSmellOfUrine { get; set; }
        public float ContinuousFeelOfUrine { get; set; }
        public float PassageOfGases { get; set; }
        public float InternalItching { get; set; }
        public float ToxicLookTyphos { get; set; }
        public float Depression { get; set; }
        public float Irritability { get; set; }
        public float MusclePain { get; set; }
        public float AlteredSensorium { get; set; }
        public float RedSpotsOverBody { get; set; }
        public float BellyPain { get; set; }
        public float AbnormalMenstruation { get; set; }
        public float DischromicPatches { get; set; }
        public float WateringFromEyes { get; set; }
        public float IncreasedAppetite { get; set; }
        public float Polyuria { get; set; }
        public float FamilyHistory { get; set; }
        public float MucoidSputum { get; set; }
        public float RustySputum { get; set; }
        public float LackOfConcentration { get; set; }
        public float VisualDisturbances { get; set; }
        public float ReceivingBloodTransfusion { get; set; }
        public float ReceivingUnsterileInjections { get; set; }
        public float Coma { get; set; }
        public float StomachBleeding { get; set; }
        public float DistentionOfAbdomen { get; set; }
        public float HistoryOfAlcoholConsumption { get; set; }
        public float FluidOverload2 { get; set; }
        public float BloodInSputum { get; set; }
        public float ProminentVeinsOnCalf { get; set; }
        public float Palpitations { get; set; }
        public float PainfulWalking { get; set; }
        public float PusFilledPimples { get; set; }
        public float Blackheads { get; set; }
        public float Scurring { get; set; }
        public float SkinPeeling { get; set; }
        public float SilverLikeDusting { get; set; }
        public float SmallDentsInNails { get; set; }
        public float InflammatoryNails { get; set; }
        public float Blister { get; set; }
        public float RedSoreAroundNose { get; set; }
        public float YellowCrustOoze { get; set; }
    }
}
